[[plugins]]
package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
    branches = ['*']
    disabled = false
    pathPrefix = "/docs"
    customDomain = "hiro.so"
    renderJavaScript = true
