name: linkcheck
on:
  pull_request:
    branches: [main]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".github/mlc_config.json"
